### create pack
POST http://localhost:5000/pack/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNAYy5jb20iLCJzdWIiOjE1LCJyb2xlcyI6InVzZXIiLCJpYXQiOjE2NTA0NzUyODgsImV4cCI6MTY1MzA2NzI4OH0.kgPHR-1LnBB51FvOISpt7emZv9xyb2w8AXkQ_sXb2RA

{
"crm":false,
"stock":true,
"order":true,
"article": true,
"user":false,
"date":"12-2-2020"
}

### Update pack
PATCH  http://localhost:5000/pack/1
Content-Type: application/json

{
  "phone": "imadox",
  "reference": "1222"
}

### Find by pack
GET http://localhost:5000/pack/id/1

### delete pack 
DELETE  http:localhost:5000/pack/id/1