### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "nouhailaskitina6@gmail.com",
  "password": "Nouha123@"
}
###
@token = {{ loginAPI.response.body.$.access_token }}

### Create product
POST {{url}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "price": 50,
  "title": "Good Pants",
  "image": "imag1",
  "rating": 4.5,
  "stock": 15,
  "description":"description",
  "category":"blouse"
}

### Update products
PATCH  {{url}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "stock": 8
}

### Find a product
GET {{url}}/products/1
Authorization: Bearer {{token}}

### Find all products
GET {{url}}/products
Authorization: Bearer {{token}}
