### Create company
POST http://localhost:5000/companies/
Content-Type: application/json

{
    "firstName": "imad",
    "lastName": "Machi",
    "email": "c3@c.com",
    "password": "test1234",
    "field": "IT",
    "size": 8,
    "socialReason": "testo",
    "address": "test 12 imagine",
    "city": "agadir",
    "country": "morocco",
    "fix": "05********",
    "phone": "06********"
}

### Update company
PATCH  http://localhost:5000/companies/4
Content-Type: application/json

{
  "firstName": "imadox",
  "email": "test@test.com"
}

### Find all companies
GET http://localhost:5000/companies

### Find by email
GET http://localhost:5000/companies/c@c.com

### Toggle isActive
GET http://localhost:5000/companies/toggle-active/4