### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "nouhailaskitina6@gmail.com",
  "password": "test1234"
}
###
@token = {{ loginAPI.response.body.$.access_token }}

### Create Stock
POST {{url}}/stocks?productId=2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "qty": 20,
  "creationDate": "2022-05-17T11:51:32.198Z",
  "warehouse": "wh1"
}

### Update products
PATCH  {{url}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "stock": 8
}

### Find a product
GET {{url}}/products/1
Authorization: Bearer {{token}}

### Find all products
GET {{url}}/products
Authorization: Bearer {{token}}


