### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "imadoxmachi@gmail.com",
  "password": "Qwerty@1234"
}
###
@token = {{ loginAPI.response.body.$.access_token }}

### Create Stock
POST {{url}}/stocks?productId=26
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "qty": 20,
  "creationDate": "2022-05-17"
}

### Update a stock
PATCH  {{url}}/stocks/21
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "qty": 5,
  "creationDate": "2022-05-15"
}

### Find a stock
GET {{url}}/stocks/21
Authorization: Bearer {{token}}

### Delete a stock
delete {{url}}/stocks/20
Authorization: Bearer {{token}}

### Find all stocks
GET {{url}}/stocks
Authorization: Bearer {{token}}


### Test
POST {{url}}/stocks/test
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "qty": 15,
  "id": 10
}