### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "imadoxmachi@gmail.com",
  "password": "Qwerty@1234"
}
###
@token = {{ loginAPI.response.body.$.access_token }}

### Get profile
GET {{url}}/users/profile
Authorization: Bearer {{token}}

### Update profile
PATCH  {{url}}/users/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstName": "Imadox"
}

### Find all users (roles = admin)
GET {{url}}/users
Authorization: Bearer {{token}}

### Find by email (roles = admin)
GET {{url}}/users/c@c.com
Authorization: Bearer {{token}}

### Toggle isActive (roles = admin)
GET {{url}}/users/toggle-active/nouhailaskitina6@gmail.com
Authorization: Bearer {{token}}
