### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "imadoxmachi@gmail.com",
  "password": "Qwerty@1234"
}
###
@token = {{ loginAPI.response.body.access_token }}

### Create order
POST {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "paymentMethod": "visa",
  "creationDate": "2022-05-19T10:54:07.902Z",
  "vat": 20,
  "customerId": 6,
  "products": [{"id": 10, "qty": 10}]
}

### Update order
PATCH  {{url}}/orders/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phone": "872726263"
}

### Find a orders
GET {{url}}/orders/3
Authorization: Bearer {{token}}

### Find all orders
GET {{url}}/orders
Authorization: Bearer {{token}}
