### create order

POST http://localhost:5000/orders/
Content-Type: application/json

{
 "description":"mamahhahah",
 "reference":122,
 "date":"12-02-12"

}

### Update order
PATCH  http://localhost:5000/orders/1
Content-Type: application/json

{
  "description": "imadox",
  "numBill": "1222f"
}

### Find by order
GET http://localhost:5000/orders/id/1

### delete order 
DELETE  http:localhost:5000/orders/id/1