### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "nouhailaskitina6@gmail.com",
  "password": "Nouha123@"
}
###
@token = {{ loginAPI.response.body.access_token }}

### Create order
POST {{url}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "billingName":"skitina",
  "totalPrice":120,
  "paymentMethod":"visa",
  "paymentStatus":"paid",
  "creationDate": "2022-05-19T10:54:07.902Z",
  "paymentDate": "2022-05-19T10:54:07.902Z",
  "deliveringDate": "2022-05-19T10:54:07.902Z",
  "isDelivered": false,
  "vat": 20,
  "customerId":7,
  "products":[{"id": 11, "qty": 3},{"id": 12, "qty": 3},{"id": 13, "qty": 3},{"id": 14, "qty": 3},{"id": 15, "qty": 3},{"id": 16, "qty": 3},{"id": 17, "qty": 3},{"id": 18, "qty": 3},{"id": 19, "qty": 3},{"id": 20, "qty": 3},{"id": 21, "qty": 3},{"id": 22, "qty": 3},{"id": 23, "qty": 3},{"id": 24, "qty": 3}]
}

### Update order

PATCH  {{url}}/orders/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phone": "872726263"
}

### Find a orders
GET {{url}}/orders/3
Authorization: Bearer {{token}}

### Find all orders
GET {{url}}/orders
Authorization: Bearer {{token}}
