### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "imadoxmachi@gmail.com",
  "password": "Qwerty@1234"
}
###
@token = {{ loginAPI.response.body.$.access_token }}

### Create a quote
POST {{url}}/quotes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "customerId": 6,
  "creationDate": "2022-05-19",
  "vat": 20,
  "products": [{"id": 7, "qty": 8}]
}

### Find all quotes
GET {{url}}/quotes
Authorization: Bearer {{token}}


### delete a quote
DELETE {{url}}/quotes/12
Authorization: Bearer {{token}}
