### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "nouhailaskitina6@gmail.com",
  "password": "Nouha123@"
}
###
@token = {{ loginAPI.response.body.$.access_token }}

### Create a quote
POST {{url}}/quotes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "supplierId": 1,
  "creationDate": "2022-05-19",
  "products": [{"id": 5, "qty": 3}]
}

### Find all quotes
GET {{url}}/quotes
Authorization: Bearer {{token}}


### delete a quote
DELETE {{url}}/quotes/1
Authorization: Bearer {{token}}
