### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "nouhailaskitina6@gmail.com",
  "password": "Nouha123@"
}
###
@token = {{ loginAPI.response.body.$.access_token }}


### create bill
GET http://localhost:5000/bills
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "orderId": 31
}

### Update bill
PATCH  http://localhost:5000/bills/1
Content-Type: application/json

{
  "description": "imadox",
  "numBill": "1222f"
}

### Find by bill
GET http://localhost:5000/bills/id/1

### delete bill 
DELETE  http:localhost:5000/bills/id/1