### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
"billingName":"skitina",
"total":123,
"paymentMethod":"visa",
"paymentStatus":"paid",
"customerId":2,
"orderLines":,
"customersLine":,
"product":
}
###
@token = {{ loginAPI.response.body.$.access_token }}

### Create order
POST {{url}}/orders/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "deleted",
  "email": "deleted@gmail.com",
  "address": "Nowhere",
  "phone": "0603065801",
  "isDeleted": true
}

### Update customer
PATCH  {{url}}/customers/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phone": "872726263"
}

### Find a customer
GET {{url}}/customers/3
Authorization: Bearer {{token}}

### Find all orders
GET {{url}}/orders/customer/1
Authorization: Bearer {{token}}
