### create User

POST http://localhost:5000/users/
Content-Type: application/json

{
  
    "lastName": "nouhaila",
    "firstName":"skitina",
   "password":"mama",
    "phone": "0603444",
    "email": "nouhailaskitina@gmail.com",
   "role":"hhaga"
    
}

### Update user
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
  "phone": "imadox",
  "email": "imran@skitina"
}

### Find by customer
GET http://localhost:5000/users/email/nouhailaskitina@gmail.com