### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "admin"
}
###
@token = {{ loginAPI.response.body.$.access_token }}

### Create customer
POST {{url}}/customers/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "skitina nouhail",
  "email": "skitinanouhail44@gmail.com",
  "address": "Bab lakhmiss, Derb Foura, 28",
  "phone": "0603065801"
}

### Update customer
PATCH  {{url}}/customers/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "phone": "872726263"
}

### Find a customer
GET {{url}}/customers/3
Authorization: Bearer {{token}}

### Find all customers
GET {{url}}/customers
Authorization: Bearer {{token}}
