### Create accounts
POST http://localhost:5000/accounts/
Content-Type: application/json

{
  
    "socialReason": "imad",
    "address": "Machi",
    "zip": "c2@c.com",
    "city": "test1234",
    "country":"maroc",
    "phone": "0603444",
    "rc": 8,
    "ice": 89999,
    "ref": "12222",
    "currency": "agadir"   
}

### Update account
PATCH  http://localhost:5000/accounts/1
Content-Type: application/json

{
  "phone": "imadox",
  "rc": "test@test.com"
}

### Find by account
GET http://localhost:5000/accounts/ref/12222