### create pack

POST http://localhost:5000/pack/
Content-Type: application/json

{
  "ref":"1233",
"price":1222,
"description":"ejjaas",
"date":"30-07-2000"
   

}

### Update pack
PATCH  http://localhost:5000/pack/1
Content-Type: application/json

{
  "description": "imadox",
  "ref": "1222"
}

### Find by pack
GET http://localhost:5000/pack/id/1

### delete pack 
DELETE  http:localhost:5000/pack/id/1