### Login user
# @name loginAPI
POST {{url}}/auth/login
Content-Type: application/json

{
  "email": "imadoxmachi@gmail.com",
  "password": "Azerty@1234"
}
###
@token = {{ loginAPI.response.body.$.access_token }}

### signup user
POST {{url}}/auth/signup
Content-Type: application/json

{
  "lastName": "nouhaila",
  "firstName":"skitina",
  "password":"Nouha123@",
  "phone": "0603444",
  "email": "nouhailaskitina6@gmail.com",
  "field": "test",
  "size": 2,
  "socialReason": "test",
  "address": "test",
  "city": "agadir",
  "country": "Morocco",
  "fix": "+21255458789"
}

### change password
PATCH {{url}}/auth/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "Qwerty@1234",
  "newPassword": "Azerty@1234"
}